openapi: "3.0.0"
info:
  version: 1.0.0
  title: Currency Exchange
servers:
  - url: http://localhost:8080
paths:
  /v1/exchange:
    post:
      summary: Currency Exchange
      operationId: exchange
      requestBody:
        description: JSON object containing exchange information
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExchangeInformationModel"
      responses:
        '200':
          description: JSON object containing exchange information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExchangeInformationModel"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorModel"
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorModel"

components:
  schemas:
    ApiErrorModel:
      properties:
        ErrorMessage:
          type: string

    ExchangeInformationModel:
      required:
        - SpendCurrency
        - PurchaseCurrency
      properties:
        SpendAmount:
          type: string
        SpendCurrency:
          type: string
        PurchaseAmount:
          type: string
        PurchaseCurrency:
          type: string